title:            "deadtrees"
url:              http://deadtrees.github.io
permalink:        pretty
highlighter:      pygments
timezone:         New Zealand/Wellington
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
